"""Provider 중립 Model과 Run 계약."""

from rigmetry.models.adapters import (
    JsonTransport,
    ModelAdapterError,
    OllamaAdapter,
    OpenAICompatibleAdapter,
    UrllibJsonTransport,
)
from rigmetry.models.contracts import (
    EvaluatorResult,
    MessageRole,
    ModelAdapter,
    ModelMessage,
    ModelRequest,
    ModelResult,
    ProviderCapabilities,
    RunResult,
    RunTerminationReason,
    Sha256Digest,
    TokenTotalSource,
    TokenUsage,
    ToolCall,
    ToolDefinition,
    ToolResult,
    canonical_json_bytes,
)

__all__ = [
    "EvaluatorResult",
    "JsonTransport",
    "MessageRole",
    "ModelAdapter",
    "ModelAdapterError",
    "ModelMessage",
    "ModelRequest",
    "ModelResult",
    "OllamaAdapter",
    "OpenAICompatibleAdapter",
    "ProviderCapabilities",
    "RunResult",
    "RunTerminationReason",
    "Sha256Digest",
    "TokenTotalSource",
    "TokenUsage",
    "ToolCall",
    "ToolDefinition",
    "ToolResult",
    "UrllibJsonTransport",
    "canonical_json_bytes",
]
